spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userDb
    username: postgres
    password: Ai310885
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 9090
  http2:
    enabled: true

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
    reactor:
      netty:
        http:
          client: DEBUG